### ISSUE TITLE
question about infinite loop

### ISSUE THREAD

**Issue by nobodxbodon** [webyrd/webmk#4]
I loaded minikanren using [CodeFromTheReasonedSchemer2ndEd](https://github.com/TheReasonedSchemer2ndEd/CodeFromTheReasonedSchemer2ndEd), then started the [interactive Tutorial](http://io.livecode.ch/learn/webyrd/webmk).

Sample codes runs fine until this part below. It does result in infinite loop as described:
```
(run* (q)
  (let loop ()
    (conde
      ((== #f q))
      ((== #t q))
      ((loop)))))
```
Then I try with `run n` as instructed below:
> If we replace * by a natural number n, then an n-element list of alternating #f's and #t's is returned. 

with code below:
```
(run 3 (q)
  (let loop ()
    (conde
      ((== #f q))
      ((== #t q))
      ((loop)))))
```
but still it seems to go infinite loop. Anything I miss here?

Thanks!

**Comment by nobodxbodon** [comment]
BTW I'm using Chez Scheme Version 9.5.

**Comment by nobodxbodon** [comment]
I just tried with [miniKanren for interactive tutorials on the web](https://github.com/webyrd/webmk), and it behaves differently:
```
> (run 3 (q)
    (let loop ()
      (conde
        ((== #f q))
        ((== #t q))
        ((loop)))))
(#f #t #f)
```

**Comment by chansey97** [comment]
TheReasonedSchemer2ndEd minikanren implementation only put a suspension on the relation which is defined by `defrel`. 

Therefore if your goal produces an infinite number of results by Scheme's `named let` instead of minikanren's `defrel`, it may go infinite loop.

A workaround is wrapping a suspension, like:

```
(define-syntax Zzz
    (syntax-rules ()
        [(_ g) (λ (s) (λ () (g s)))]))

(run 3 q
     (let loop ()
       (Zzz (conde
             ((== #f q))
             ((== #t q))
             ((loop)))) ))
;; => '(#f #t #f)   
```
